source ~/.prompt

export PATH=/usr/local/bin:$PATH

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # This loads RVM into a shell session.
PATH=$PATH:$HOME/.rvm/bin

alias desk='cd ~/Desktop'
alias fingers-crossed='bundle exec spec'
alias b='bundle exec'
alias op='cd ~/Desktop/operator_api'
alias ops='cd ~/Desktop/operator_api_stubs/'
alias wap='cd ~/Desktop/migpay_3/wap'
alias admin='cd ~/Desktop/migpay_3/admin'
alias v='mvim'
alias ll="ls -la"
alias ls="ls -G"
alias dir="mkdir"
alias jg="cd ~/Desktop/justgiving"
alias jgm="cd ~/Desktop/justgiving_mocks"
alias iterm="open /Users/aali/Downloads/iTerm.app/"
alias q="b rake spec SPEC="
alias storm='cd ~/Desktop/storm_crow'

alias bashinstall='ruby ~/dotfile/install.rb'

alias trello='open https://trello.com/'
alias github='open https://github.com/'
alias github_migpay='open https://github.com/mitadmin/migpay_3'
alias github_jg='open https://github.com/mitadmin/justgiving'
alias github_oap='open https://github.com/mitadmin/operator_api'
alias abdullah='echo he is awesome'

/* git */
alias x='gitx'
alias dev='git checkout development'
alias gg="git grep --color"
alias pull='git pull'
alias push='git push origin `git rev-parse --abbrev-ref HEAD`'
alias branch='git branch'
alias newbranch='git checkout -b'
alias status='git status'

if [ -f ~/.git-completion.bash ]; then
  . ~/.git-completion.bash
fi

export TERM=xterm

ssh-add

alias grep='grep --color'

export GREP_COLOR=32
export LSCOLORS=ExFxCxDxBxegedabagacad

##
# Your previous /Users/aali/.bash_profile file was backed up as /Users/aali/.bash_profile.macports-saved_2012-11-20_at_16:25:31
##

# MacPorts Installer addition on 2012-11-20_at_16:25:31: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

