source ~/.prompt

export PATH=/usr/local/bin:$PATH

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # This loads RVM into a shell session.
PATH=$PATH:$HOME/.rvm/bin

alias desk='cd ~/Desktop'
alias b='bundle exec'
alias x='gitx'
